
POST http://localhost:3333/workspace HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImlhdCI6MTU5ODU4ODY2N30.8raichj4DDEn4aALky1mFF9Y0SQ7G8IQPMJRyYnBc0o

{
 "name": "Terceiro",
 "description": "Terceiro Workspace"
}

###
PUT http://localhost:3333/workspace/7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImlhdCI6MTU5ODU4ODY2N30.8raichj4DDEn4aALky1mFF9Y0SQ7G8IQPMJRyYnBc0o

{
 "name": "Final",
 "description": "Final Workspace"
}

###
GET http://localhost:3333/workspace HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImlhdCI6MTU5ODU4ODY2N30.8raichj4DDEn4aALky1mFF9Y0SQ7G8IQPMJRyYnBc0o

###
GET http://localhost:3333/workspace/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImlhdCI6MTU5ODU4ODY2N30.8raichj4DDEn4aALky1mFF9Y0SQ7G8IQPMJRyYnBc0o

###
DELETE http://localhost:3333/workspace/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImlhdCI6MTU5ODU4ODY2N30.8raichj4DDEn4aALky1mFF9Y0SQ7G8IQPMJRyYnBc0o
